@startuml
state default {
[*] --> RCVPCKT : CTRL[{it == CharacterConstants.SOH}]
RCVPCKT --> RCVDATA : CTRL[{it == CharacterConstants.STX}] :: {  addField();  }
RCVPCKT --> RCVCHK : BYTE :: {  addChecksum(it);  }
RCVDATA --> RCVDATA : BYTE :: {  addByte(it);  }
RCVDATA --> RCVPCKT : CTRL[{it == CharacterConstants.ETX}] :: {  endField();  }
RCVDATA --> RCVESC : ESC
RCVESC --> RCVDATA : ESC :: {  addByte(CharacterConstants.ESC);  }
RCVESC --> RCVDATA : CTRL :: {  addByte(it);  }
RCVCHK --> RCVCHK : BYTE :: {  addChecksum(it);  }
RCVCHK --> RCVCHKESC : ESC
RCVCHK --> CHKSUM : CTRL[{it == CharacterConstants.EOT}] :: {  checksum();  }
CHKSUM --> [*] : <<automatic>>[{!checksumValid}] :: {  sendNACK();  }
CHKSUM --> [*] : <<automatic>>[{checksumValid}] :: {  sendACK();  }
RCVCHKESC --> RCVCHK : ESC :: {  addChecksum(CharacterConstants.ESC);  }
RCVCHKESC --> RCVCHK : CTRL :: {byte->  require(byte != null);  addChecksum(byte);  }
}
@enduml
