@startuml
skinparam StateFontName Helvetica
skinparam defaultFontName Monospaced
skinparam state {
    BackgroundColor LightBlue
}
state PacketReaderFSM {
[*] --> RCVPCKT : CTRL [{it == CharacterConstants.SOH}]
RCVPCKT --> RCVDATA : CTRL [{it == CharacterConstants.STX}]\l<<action>> {\laddField()\l}
RCVPCKT --> RCVCHK : BYTE\l<<action>> {\laddChecksum(it)\l}
RCVDATA --> RCVDATA : BYTE\l<<action>> {\laddByte(it)\l}
RCVDATA --> RCVPCKT : CTRL [{it == CharacterConstants.ETX}]\l<<action>> {\lendField()\l}
RCVDATA --> RCVESC : ESC
RCVESC --> RCVDATA : ESC\l<<action>> {\laddByte(CharacterConstants.ESC)\l}
RCVESC --> RCVDATA : CTRL\l<<action>> {\laddByte(it)\l}
RCVCHK --> RCVCHK : BYTE\l<<action>> {\laddChecksum(it)\l}
RCVCHK --> RCVCHKESC : ESC
RCVCHK --> CHKSUM : CTRL [{it == CharacterConstants.EOT}]\l<<action>> {\lchecksum()\l}
CHKSUM --> [*] : <<automatic>> [{!checksumValid}]\l<<action>> {\lsendNACK()\l}
CHKSUM --> [*] : <<automatic>> [{checksumValid}]\l<<action>> {\lsendACK()\l}
RCVCHKESC --> RCVCHK : ESC\l<<action>> {\laddChecksum(CharacterConstants.ESC)\l}
RCVCHKESC --> RCVCHK : CTRL\l<<action>> {byte->\lrequire(byte != null)\laddChecksum(byte)\l}
}
@enduml
