@startuml
skinparam StateFontName Helvetica
skinparam defaultFontName Monospaced
state SecureTurnstileFSM {
LOCKED --> LOCKED : CARD [{cardId->requireNotNull(cardId);isOverrideCard(cardId)&&overrideActive;}]\l<<action>> {\lcancelOverride()\l}
LOCKED --> LOCKED : CARD [{cardId->requireNotNull(cardId);isOverrideCard(cardId);}]\l<<action>> {\lactivateOverride()\l}
LOCKED --> UNLOCKED : CARD [{cardId->requireNotNull(cardId);overrideActive||isValidCard(cardId);}]\l<<action>> {\lunlock()\l}
LOCKED --> LOCKED : CARD [{cardId->requireNotNull(cardId){"cardId is required"};!isValidCard(cardId);}]\l<<action>> {cardId->\lrequireNotNull(cardId)\linvalidCard(cardId)\l}
UNLOCKED --> LOCKED : CARD [{cardId->requireNotNull(cardId);isOverrideCard(cardId);}]\l<<action>> {\llock()\l}
UNLOCKED --> LOCKED : PASS\l<<action>> {\llock()\l}
}
@enduml
