@startuml
skinparam monochrome true
skinparam StateFontName Helvetica
skinparam defaultFontName Monospaced
skinparam defaultFontStyle Bold
skinparam state {
    FontStyle Bold
}
state TurnstileFSM {
[*] --> UNLOCKED
LOCKED --> UNLOCKED : COIN
UNLOCKED --> LOCKED : PASS
UNLOCKED --> UNLOCKED : COIN
}
@enduml
